
CREATE TABLE bid_review (
    id VARCHAR PRIMARY KEY,
    bid_id VARCHAR REFERENCES bid(id) ON DELETE CASCADE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);