CREATE TABLE bid_review (
    id VARCHAR PRIMARY KEY, 
    bid_id VARCHAR NOT NULL REFERENCES bid(id) ON DELETE CASCADE, 
    description TEXT,    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);